/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 src/assets/models/core/player-barbarian.glb --transform --types 
Files: src/assets/models/core/player-barbarian.glb [392.47KB] > /Users/roblibob/Projects/DungeonPlanner/player-barbarian-transformed.glb [74.73KB] (81%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { GLTF, SkeletonUtils } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Barbarian_ArmLeft: THREE.SkinnedMesh
    Barbarian_ArmRight: THREE.SkinnedMesh
    Barbarian_BearHat: THREE.SkinnedMesh
    Barbarian_Body: THREE.SkinnedMesh
    Barbarian_Head: THREE.SkinnedMesh
    Barbarian_LegLeft: THREE.SkinnedMesh
    Barbarian_LegRight: THREE.SkinnedMesh
    root: THREE.Bone
  }
  materials: {
    ['barbarian.001']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { scene } = useGLTF('/player-barbarian-transformed.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as GLTFResult
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes.root} />
      <skinnedMesh geometry={nodes.Barbarian_ArmLeft.geometry} material={materials['barbarian.001']} skeleton={nodes.Barbarian_ArmLeft.skeleton} />
      <skinnedMesh geometry={nodes.Barbarian_ArmRight.geometry} material={materials['barbarian.001']} skeleton={nodes.Barbarian_ArmRight.skeleton} />
      <skinnedMesh geometry={nodes.Barbarian_BearHat.geometry} material={materials['barbarian.001']} skeleton={nodes.Barbarian_BearHat.skeleton} />
      <skinnedMesh geometry={nodes.Barbarian_Body.geometry} material={materials['barbarian.001']} skeleton={nodes.Barbarian_Body.skeleton} />
      <skinnedMesh geometry={nodes.Barbarian_Head.geometry} material={materials['barbarian.001']} skeleton={nodes.Barbarian_Head.skeleton} />
      <skinnedMesh geometry={nodes.Barbarian_LegLeft.geometry} material={materials['barbarian.001']} skeleton={nodes.Barbarian_LegLeft.skeleton} />
      <skinnedMesh geometry={nodes.Barbarian_LegRight.geometry} material={materials['barbarian.001']} skeleton={nodes.Barbarian_LegRight.skeleton} />
    </group>
  )
}

useGLTF.preload('/player-barbarian-transformed.glb')
