import { createKayKitAsset, type KayKitTransform } from '../shared/createKayKitAsset'

const TREE_TRANSFORM = {
  position: [0, 0, 0] as const,
  rotation: [0, 0, 0] as const,
  scale: [3, 3, 3],
} satisfies KayKitTransform

const ROCK_BUSH_TRANSFORM = {
  position: [0, 0, 0] as const,
  rotation: [0, 0, 0] as const,
  scale: [1.6, 1.6, 1.6],
} satisfies KayKitTransform

const GRASS_TRANSFORM = {
  position: [0, 0, 0] as const,
  rotation: [0, 0, 0] as const,
  scale: [1.5, 1.5, 1.5],
} satisfies KayKitTransform

export const kaykitAdditionalForestAssets = [
  createKayKitAsset({
    id: 'kaykit.forest_bush_1_b',
    slug: 'kaykit-forest-bush-1-b',
    name: 'KayKit Forest Bush 1 B',
    category: 'prop',
    modelName: 'Bush_1_B_Color1',
    transform: ROCK_BUSH_TRANSFORM,
    metadata: {
      connectsTo: 'FLOOR',
      blocksLineOfSight: true,
    },
  }),
  createKayKitAsset({
    id: 'kaykit.forest_bush_1_c',
    slug: 'kaykit-forest-bush-1-c',
    name: 'KayKit Forest Bush 1 C',
    category: 'prop',
    modelName: 'Bush_1_C_Color1',
    transform: ROCK_BUSH_TRANSFORM,
    metadata: {
      connectsTo: 'FLOOR',
      blocksLineOfSight: true,
    },
  }),
  createKayKitAsset({
    id: 'kaykit.forest_bush_1_d',
    slug: 'kaykit-forest-bush-1-d',
    name: 'KayKit Forest Bush 1 D',
    category: 'prop',
    modelName: 'Bush_1_D_Color1',
    transform: ROCK_BUSH_TRANSFORM,
    metadata: {
      connectsTo: 'FLOOR',
      blocksLineOfSight: true,
    },
  }),
  createKayKitAsset({
    id: 'kaykit.forest_bush_1_e',
    slug: 'kaykit-forest-bush-1-e',
    name: 'KayKit Forest Bush 1 E',
    category: 'prop',
    modelName: 'Bush_1_E_Color1',
    transform: ROCK_BUSH_TRANSFORM,
    metadata: {
      connectsTo: 'FLOOR',
      blocksLineOfSight: true,
    },
  }),
  createKayKitAsset({
    id: 'kaykit.forest_bush_1_f',
    slug: 'kaykit-forest-bush-1-f',
    name: 'KayKit Forest Bush 1 F',
    category: 'prop',
    modelName: 'Bush_1_F_Color1',
    transform: ROCK_BUSH_TRANSFORM,
    metadata: {
      connectsTo: 'FLOOR',
      blocksLineOfSight: true,
    },
  }),
  createKayKitAsset({
    id: 'kaykit.forest_bush_1_g',
    slug: 'kaykit-forest-bush-1-g',
    name: 'KayKit Forest Bush 1 G',
    category: 'prop',
    modelName: 'Bush_1_G_Color1',
    transform: ROCK_BUSH_TRANSFORM,
    metadata: {
      connectsTo: 'FLOOR',
      blocksLineOfSight: true,
    },
  }),
  createKayKitAsset({
    id: 'kaykit.forest_bush_2_b',
    slug: 'kaykit-forest-bush-2-b',
    name: 'KayKit Forest Bush 2 B',
    category: 'prop',
    modelName: 'Bush_2_B_Color1',
    transform: ROCK_BUSH_TRANSFORM,
    metadata: {
      connectsTo: 'FLOOR',
      blocksLineOfSight: true,
    },
  }),
  createKayKitAsset({
    id: 'kaykit.forest_bush_2_c',
    slug: 'kaykit-forest-bush-2-c',
    name: 'KayKit Forest Bush 2 C',
    category: 'prop',
    modelName: 'Bush_2_C_Color1',
    transform: ROCK_BUSH_TRANSFORM,
    metadata: {
      connectsTo: 'FLOOR',
      blocksLineOfSight: true,
    },
  }),
  createKayKitAsset({
    id: 'kaykit.forest_bush_2_d',
    slug: 'kaykit-forest-bush-2-d',
    name: 'KayKit Forest Bush 2 D',
    category: 'prop',
    modelName: 'Bush_2_D_Color1',
    transform: ROCK_BUSH_TRANSFORM,
    metadata: {
      connectsTo: 'FLOOR',
      blocksLineOfSight: true,
    },
  }),
  createKayKitAsset({
    id: 'kaykit.forest_bush_2_e',
    slug: 'kaykit-forest-bush-2-e',
    name: 'KayKit Forest Bush 2 E',
    category: 'prop',
    modelName: 'Bush_2_E_Color1',
    transform: ROCK_BUSH_TRANSFORM,
    metadata: {
      connectsTo: 'FLOOR',
      blocksLineOfSight: true,
    },
  }),
  createKayKitAsset({
    id: 'kaykit.forest_bush_2_f',
    slug: 'kaykit-forest-bush-2-f',
    name: 'KayKit Forest Bush 2 F',
    category: 'prop',
    modelName: 'Bush_2_F_Color1',
    transform: ROCK_BUSH_TRANSFORM,
    metadata: {
      connectsTo: 'FLOOR',
      blocksLineOfSight: true,
    },
  }),
  createKayKitAsset({
    id: 'kaykit.forest_bush_3_b',
    slug: 'kaykit-forest-bush-3-b',
    name: 'KayKit Forest Bush 3 B',
    category: 'prop',
    modelName: 'Bush_3_B_Color1',
    transform: ROCK_BUSH_TRANSFORM,
    metadata: {
      connectsTo: 'FLOOR',
      blocksLineOfSight: true,
    },
  }),
  createKayKitAsset({
    id: 'kaykit.forest_bush_3_c',
    slug: 'kaykit-forest-bush-3-c',
    name: 'KayKit Forest Bush 3 C',
    category: 'prop',
    modelName: 'Bush_3_C_Color1',
    transform: ROCK_BUSH_TRANSFORM,
    metadata: {
      connectsTo: 'FLOOR',
      blocksLineOfSight: true,
    },
  }),
  createKayKitAsset({
    id: 'kaykit.forest_bush_4_a',
    slug: 'kaykit-forest-bush-4-a',
    name: 'KayKit Forest Bush 4 A',
    category: 'prop',
    modelName: 'Bush_4_A_Color1',
    transform: ROCK_BUSH_TRANSFORM,
    metadata: {
      connectsTo: 'FLOOR',
      blocksLineOfSight: true,
    },
  }),
  createKayKitAsset({
    id: 'kaykit.forest_bush_4_b',
    slug: 'kaykit-forest-bush-4-b',
    name: 'KayKit Forest Bush 4 B',
    category: 'prop',
    modelName: 'Bush_4_B_Color1',
    transform: ROCK_BUSH_TRANSFORM,
    metadata: {
      connectsTo: 'FLOOR',
      blocksLineOfSight: true,
    },
  }),
  createKayKitAsset({
    id: 'kaykit.forest_bush_4_c',
    slug: 'kaykit-forest-bush-4-c',
    name: 'KayKit Forest Bush 4 C',
    category: 'prop',
    modelName: 'Bush_4_C_Color1',
    transform: ROCK_BUSH_TRANSFORM,
    metadata: {
      connectsTo: 'FLOOR',
      blocksLineOfSight: true,
    },
  }),
  createKayKitAsset({
    id: 'kaykit.forest_bush_4_d',
    slug: 'kaykit-forest-bush-4-d',
    name: 'KayKit Forest Bush 4 D',
    category: 'prop',
    modelName: 'Bush_4_D_Color1',
    transform: ROCK_BUSH_TRANSFORM,
    metadata: {
      connectsTo: 'FLOOR',
      blocksLineOfSight: true,
    },
  }),
  createKayKitAsset({
    id: 'kaykit.forest_bush_4_e',
    slug: 'kaykit-forest-bush-4-e',
    name: 'KayKit Forest Bush 4 E',
    category: 'prop',
    modelName: 'Bush_4_E_Color1',
    transform: ROCK_BUSH_TRANSFORM,
    metadata: {
      connectsTo: 'FLOOR',
      blocksLineOfSight: true,
    },
  }),
  createKayKitAsset({
    id: 'kaykit.forest_bush_4_f',
    slug: 'kaykit-forest-bush-4-f',
    name: 'KayKit Forest Bush 4 F',
    category: 'prop',
    modelName: 'Bush_4_F_Color1',
    transform: ROCK_BUSH_TRANSFORM,
    metadata: {
      connectsTo: 'FLOOR',
      blocksLineOfSight: true,
    },
  }),
  createKayKitAsset({
    id: 'kaykit.forest_grass_1_a',
    slug: 'kaykit-forest-grass-1-a',
    name: 'KayKit Forest Grass 1 A',
    category: 'prop',
    modelName: 'Grass_1_A_Color1',
    transform: GRASS_TRANSFORM,
    metadata: {
      connectsTo: 'FLOOR',
    },
  }),
  createKayKitAsset({
    id: 'kaykit.forest_grass_1_a_singlesided',
    slug: 'kaykit-forest-grass-1-a-singlesided',
    name: 'KayKit Forest Grass 1 A Singlesided',
    category: 'prop',
    modelName: 'Grass_1_A_Singlesided_Color1',
    transform: GRASS_TRANSFORM,
    metadata: {
      connectsTo: 'FLOOR',
    },
  }),
  createKayKitAsset({
    id: 'kaykit.forest_grass_1_b',
    slug: 'kaykit-forest-grass-1-b',
    name: 'KayKit Forest Grass 1 B',
    category: 'prop',
    modelName: 'Grass_1_B_Color1',
    transform: GRASS_TRANSFORM,
    metadata: {
      connectsTo: 'FLOOR',
    },
  }),
  createKayKitAsset({
    id: 'kaykit.forest_grass_1_b_singlesided',
    slug: 'kaykit-forest-grass-1-b-singlesided',
    name: 'KayKit Forest Grass 1 B Singlesided',
    category: 'prop',
    modelName: 'Grass_1_B_Singlesided_Color1',
    transform: GRASS_TRANSFORM,
    metadata: {
      connectsTo: 'FLOOR',
    },
  }),
  createKayKitAsset({
    id: 'kaykit.forest_grass_1_c',
    slug: 'kaykit-forest-grass-1-c',
    name: 'KayKit Forest Grass 1 C',
    category: 'prop',
    modelName: 'Grass_1_C_Color1',
    transform: GRASS_TRANSFORM,
    metadata: {
      connectsTo: 'FLOOR',
    },
  }),
  createKayKitAsset({
    id: 'kaykit.forest_grass_1_c_singlesided',
    slug: 'kaykit-forest-grass-1-c-singlesided',
    name: 'KayKit Forest Grass 1 C Singlesided',
    category: 'prop',
    modelName: 'Grass_1_C_Singlesided_Color1',
    transform: GRASS_TRANSFORM,
    metadata: {
      connectsTo: 'FLOOR',
    },
  }),
  createKayKitAsset({
    id: 'kaykit.forest_grass_1_d',
    slug: 'kaykit-forest-grass-1-d',
    name: 'KayKit Forest Grass 1 D',
    category: 'prop',
    modelName: 'Grass_1_D_Color1',
    transform: GRASS_TRANSFORM,
    metadata: {
      connectsTo: 'FLOOR',
    },
  }),
  createKayKitAsset({
    id: 'kaykit.forest_grass_1_d_singlesided',
    slug: 'kaykit-forest-grass-1-d-singlesided',
    name: 'KayKit Forest Grass 1 D Singlesided',
    category: 'prop',
    modelName: 'Grass_1_D_Singlesided_Color1',
    transform: GRASS_TRANSFORM,
    metadata: {
      connectsTo: 'FLOOR',
    },
  }),
  createKayKitAsset({
    id: 'kaykit.forest_grass_1_mesh',
    slug: 'kaykit-forest-grass-1-mesh',
    name: 'KayKit Forest Grass 1 Mesh',
    category: 'prop',
    modelName: 'Grass_1_Mesh',
    transform: GRASS_TRANSFORM,
    metadata: {
      connectsTo: 'FLOOR',
    },
  }),
  createKayKitAsset({
    id: 'kaykit.forest_grass_1_singlesided_mesh',
    slug: 'kaykit-forest-grass-1-singlesided-mesh',
    name: 'KayKit Forest Grass 1 Single Sided Mesh',
    category: 'prop',
    modelName: 'Grass_1_SingleSided_Mesh',
    transform: GRASS_TRANSFORM,
    metadata: {
      connectsTo: 'FLOOR',
    },
  }),
  createKayKitAsset({
    id: 'kaykit.forest_grass_2_a',
    slug: 'kaykit-forest-grass-2-a',
    name: 'KayKit Forest Grass 2 A',
    category: 'prop',
    modelName: 'Grass_2_A_Color1',
    transform: GRASS_TRANSFORM,
    metadata: {
      connectsTo: 'FLOOR',
    },
  }),
  createKayKitAsset({
    id: 'kaykit.forest_grass_2_a_singlesided',
    slug: 'kaykit-forest-grass-2-a-singlesided',
    name: 'KayKit Forest Grass 2 A Singlesided',
    category: 'prop',
    modelName: 'Grass_2_A_Singlesided_Color1',
    transform: GRASS_TRANSFORM,
    metadata: {
      connectsTo: 'FLOOR',
    },
  }),
  createKayKitAsset({
    id: 'kaykit.forest_grass_2_b',
    slug: 'kaykit-forest-grass-2-b',
    name: 'KayKit Forest Grass 2 B',
    category: 'prop',
    modelName: 'Grass_2_B_Color1',
    transform: GRASS_TRANSFORM,
    metadata: {
      connectsTo: 'FLOOR',
    },
  }),
  createKayKitAsset({
    id: 'kaykit.forest_grass_2_b_singlesided',
    slug: 'kaykit-forest-grass-2-b-singlesided',
    name: 'KayKit Forest Grass 2 B Singlesided',
    category: 'prop',
    modelName: 'Grass_2_B_Singlesided_Color1',
    transform: GRASS_TRANSFORM,
    metadata: {
      connectsTo: 'FLOOR',
    },
  }),
  createKayKitAsset({
    id: 'kaykit.forest_grass_2_c',
    slug: 'kaykit-forest-grass-2-c',
    name: 'KayKit Forest Grass 2 C',
    category: 'prop',
    modelName: 'Grass_2_C_Color1',
    transform: GRASS_TRANSFORM,
    metadata: {
      connectsTo: 'FLOOR',
    },
  }),
  createKayKitAsset({
    id: 'kaykit.forest_grass_2_c_singlesided',
    slug: 'kaykit-forest-grass-2-c-singlesided',
    name: 'KayKit Forest Grass 2 C Singlesided',
    category: 'prop',
    modelName: 'Grass_2_C_Singlesided_Color1',
    transform: GRASS_TRANSFORM,
    metadata: {
      connectsTo: 'FLOOR',
    },
  }),
  createKayKitAsset({
    id: 'kaykit.forest_grass_2_d',
    slug: 'kaykit-forest-grass-2-d',
    name: 'KayKit Forest Grass 2 D',
    category: 'prop',
    modelName: 'Grass_2_D_Color1',
    transform: GRASS_TRANSFORM,
    metadata: {
      connectsTo: 'FLOOR',
    },
  }),
  createKayKitAsset({
    id: 'kaykit.forest_grass_2_d_singlesided',
    slug: 'kaykit-forest-grass-2-d-singlesided',
    name: 'KayKit Forest Grass 2 D Singlesided',
    category: 'prop',
    modelName: 'Grass_2_D_Singlesided_Color1',
    transform: GRASS_TRANSFORM,
    metadata: {
      connectsTo: 'FLOOR',
    },
  }),
  createKayKitAsset({
    id: 'kaykit.forest_grass_2_mesh',
    slug: 'kaykit-forest-grass-2-mesh',
    name: 'KayKit Forest Grass 2 Mesh',
    category: 'prop',
    modelName: 'Grass_2_Mesh',
    transform: GRASS_TRANSFORM,
    metadata: {
      connectsTo: 'FLOOR',
    },
  }),
  createKayKitAsset({
    id: 'kaykit.forest_grass_2_singlesided_mesh',
    slug: 'kaykit-forest-grass-2-singlesided-mesh',
    name: 'KayKit Forest Grass 2 Single Sided Mesh',
    category: 'prop',
    modelName: 'Grass_2_SingleSided_Mesh',
    transform: GRASS_TRANSFORM,
    metadata: {
      connectsTo: 'FLOOR',
    },
  }),
  createKayKitAsset({
    id: 'kaykit.forest_rock_1_b',
    slug: 'kaykit-forest-rock-1-b',
    name: 'KayKit Forest Rock 1 B',
    category: 'prop',
    modelName: 'Rock_1_B_Color1',
    transform: ROCK_BUSH_TRANSFORM,
    metadata: {
      connectsTo: 'FLOOR',
      blocksLineOfSight: true,
    },
  }),
  createKayKitAsset({
    id: 'kaykit.forest_rock_1_c',
    slug: 'kaykit-forest-rock-1-c',
    name: 'KayKit Forest Rock 1 C',
    category: 'prop',
    modelName: 'Rock_1_C_Color1',
    transform: ROCK_BUSH_TRANSFORM,
    metadata: {
      connectsTo: 'FLOOR',
      blocksLineOfSight: true,
    },
  }),
  createKayKitAsset({
    id: 'kaykit.forest_rock_1_d',
    slug: 'kaykit-forest-rock-1-d',
    name: 'KayKit Forest Rock 1 D',
    category: 'prop',
    modelName: 'Rock_1_D_Color1',
    transform: ROCK_BUSH_TRANSFORM,
    metadata: {
      connectsTo: 'FLOOR',
      blocksLineOfSight: true,
    },
  }),
  createKayKitAsset({
    id: 'kaykit.forest_rock_1_e',
    slug: 'kaykit-forest-rock-1-e',
    name: 'KayKit Forest Rock 1 E',
    category: 'prop',
    modelName: 'Rock_1_E_Color1',
    transform: ROCK_BUSH_TRANSFORM,
    metadata: {
      connectsTo: 'FLOOR',
      blocksLineOfSight: true,
    },
  }),
  createKayKitAsset({
    id: 'kaykit.forest_rock_1_f',
    slug: 'kaykit-forest-rock-1-f',
    name: 'KayKit Forest Rock 1 F',
    category: 'prop',
    modelName: 'Rock_1_F_Color1',
    transform: ROCK_BUSH_TRANSFORM,
    metadata: {
      connectsTo: 'FLOOR',
      blocksLineOfSight: true,
    },
  }),
  createKayKitAsset({
    id: 'kaykit.forest_rock_1_g',
    slug: 'kaykit-forest-rock-1-g',
    name: 'KayKit Forest Rock 1 G',
    category: 'prop',
    modelName: 'Rock_1_G_Color1',
    transform: ROCK_BUSH_TRANSFORM,
    metadata: {
      connectsTo: 'FLOOR',
      blocksLineOfSight: true,
    },
  }),
  createKayKitAsset({
    id: 'kaykit.forest_rock_1_h',
    slug: 'kaykit-forest-rock-1-h',
    name: 'KayKit Forest Rock 1 H',
    category: 'prop',
    modelName: 'Rock_1_H_Color1',
    transform: ROCK_BUSH_TRANSFORM,
    metadata: {
      connectsTo: 'FLOOR',
      blocksLineOfSight: true,
    },
  }),
  createKayKitAsset({
    id: 'kaykit.forest_rock_1_i',
    slug: 'kaykit-forest-rock-1-i',
    name: 'KayKit Forest Rock 1 I',
    category: 'prop',
    modelName: 'Rock_1_I_Color1',
    transform: ROCK_BUSH_TRANSFORM,
    metadata: {
      connectsTo: 'FLOOR',
      blocksLineOfSight: true,
    },
  }),
  createKayKitAsset({
    id: 'kaykit.forest_rock_1_j',
    slug: 'kaykit-forest-rock-1-j',
    name: 'KayKit Forest Rock 1 J',
    category: 'prop',
    modelName: 'Rock_1_J_Color1',
    transform: ROCK_BUSH_TRANSFORM,
    metadata: {
      connectsTo: 'FLOOR',
      blocksLineOfSight: true,
    },
  }),
  createKayKitAsset({
    id: 'kaykit.forest_rock_1_k',
    slug: 'kaykit-forest-rock-1-k',
    name: 'KayKit Forest Rock 1 K',
    category: 'prop',
    modelName: 'Rock_1_K_Color1',
    transform: ROCK_BUSH_TRANSFORM,
    metadata: {
      connectsTo: 'FLOOR',
      blocksLineOfSight: true,
    },
  }),
  createKayKitAsset({
    id: 'kaykit.forest_rock_1_l',
    slug: 'kaykit-forest-rock-1-l',
    name: 'KayKit Forest Rock 1 L',
    category: 'prop',
    modelName: 'Rock_1_L_Color1',
    transform: ROCK_BUSH_TRANSFORM,
    metadata: {
      connectsTo: 'FLOOR',
      blocksLineOfSight: true,
    },
  }),
  createKayKitAsset({
    id: 'kaykit.forest_rock_1_m',
    slug: 'kaykit-forest-rock-1-m',
    name: 'KayKit Forest Rock 1 M',
    category: 'prop',
    modelName: 'Rock_1_M_Color1',
    transform: ROCK_BUSH_TRANSFORM,
    metadata: {
      connectsTo: 'FLOOR',
      blocksLineOfSight: true,
    },
  }),
  createKayKitAsset({
    id: 'kaykit.forest_rock_1_n',
    slug: 'kaykit-forest-rock-1-n',
    name: 'KayKit Forest Rock 1 N',
    category: 'prop',
    modelName: 'Rock_1_N_Color1',
    transform: ROCK_BUSH_TRANSFORM,
    metadata: {
      connectsTo: 'FLOOR',
      blocksLineOfSight: true,
    },
  }),
  createKayKitAsset({
    id: 'kaykit.forest_rock_1_o',
    slug: 'kaykit-forest-rock-1-o',
    name: 'KayKit Forest Rock 1 O',
    category: 'prop',
    modelName: 'Rock_1_O_Color1',
    transform: ROCK_BUSH_TRANSFORM,
    metadata: {
      connectsTo: 'FLOOR',
      blocksLineOfSight: true,
    },
  }),
  createKayKitAsset({
    id: 'kaykit.forest_rock_1_p',
    slug: 'kaykit-forest-rock-1-p',
    name: 'KayKit Forest Rock 1 P',
    category: 'prop',
    modelName: 'Rock_1_P_Color1',
    transform: ROCK_BUSH_TRANSFORM,
    metadata: {
      connectsTo: 'FLOOR',
      blocksLineOfSight: true,
    },
  }),
  createKayKitAsset({
    id: 'kaykit.forest_rock_1_q',
    slug: 'kaykit-forest-rock-1-q',
    name: 'KayKit Forest Rock 1 Q',
    category: 'prop',
    modelName: 'Rock_1_Q_Color1',
    transform: ROCK_BUSH_TRANSFORM,
    metadata: {
      connectsTo: 'FLOOR',
      blocksLineOfSight: true,
    },
  }),
  createKayKitAsset({
    id: 'kaykit.forest_rock_2_b',
    slug: 'kaykit-forest-rock-2-b',
    name: 'KayKit Forest Rock 2 B',
    category: 'prop',
    modelName: 'Rock_2_B_Color1',
    transform: ROCK_BUSH_TRANSFORM,
    metadata: {
      connectsTo: 'FLOOR',
      blocksLineOfSight: true,
    },
  }),
  createKayKitAsset({
    id: 'kaykit.forest_rock_2_c',
    slug: 'kaykit-forest-rock-2-c',
    name: 'KayKit Forest Rock 2 C',
    category: 'prop',
    modelName: 'Rock_2_C_Color1',
    transform: ROCK_BUSH_TRANSFORM,
    metadata: {
      connectsTo: 'FLOOR',
      blocksLineOfSight: true,
    },
  }),
  createKayKitAsset({
    id: 'kaykit.forest_rock_2_d',
    slug: 'kaykit-forest-rock-2-d',
    name: 'KayKit Forest Rock 2 D',
    category: 'prop',
    modelName: 'Rock_2_D_Color1',
    transform: ROCK_BUSH_TRANSFORM,
    metadata: {
      connectsTo: 'FLOOR',
      blocksLineOfSight: true,
    },
  }),
  createKayKitAsset({
    id: 'kaykit.forest_rock_2_e',
    slug: 'kaykit-forest-rock-2-e',
    name: 'KayKit Forest Rock 2 E',
    category: 'prop',
    modelName: 'Rock_2_E_Color1',
    transform: ROCK_BUSH_TRANSFORM,
    metadata: {
      connectsTo: 'FLOOR',
      blocksLineOfSight: true,
    },
  }),
  createKayKitAsset({
    id: 'kaykit.forest_rock_2_f',
    slug: 'kaykit-forest-rock-2-f',
    name: 'KayKit Forest Rock 2 F',
    category: 'prop',
    modelName: 'Rock_2_F_Color1',
    transform: ROCK_BUSH_TRANSFORM,
    metadata: {
      connectsTo: 'FLOOR',
      blocksLineOfSight: true,
    },
  }),
  createKayKitAsset({
    id: 'kaykit.forest_rock_2_g',
    slug: 'kaykit-forest-rock-2-g',
    name: 'KayKit Forest Rock 2 G',
    category: 'prop',
    modelName: 'Rock_2_G_Color1',
    transform: ROCK_BUSH_TRANSFORM,
    metadata: {
      connectsTo: 'FLOOR',
      blocksLineOfSight: true,
    },
  }),
  createKayKitAsset({
    id: 'kaykit.forest_rock_2_h',
    slug: 'kaykit-forest-rock-2-h',
    name: 'KayKit Forest Rock 2 H',
    category: 'prop',
    modelName: 'Rock_2_H_Color1',
    transform: ROCK_BUSH_TRANSFORM,
    metadata: {
      connectsTo: 'FLOOR',
      blocksLineOfSight: true,
    },
  }),
  createKayKitAsset({
    id: 'kaykit.forest_rock_3_b',
    slug: 'kaykit-forest-rock-3-b',
    name: 'KayKit Forest Rock 3 B',
    category: 'prop',
    modelName: 'Rock_3_B_Color1',
    transform: ROCK_BUSH_TRANSFORM,
    metadata: {
      connectsTo: 'FLOOR',
      blocksLineOfSight: true,
    },
  }),
  createKayKitAsset({
    id: 'kaykit.forest_rock_3_c',
    slug: 'kaykit-forest-rock-3-c',
    name: 'KayKit Forest Rock 3 C',
    category: 'prop',
    modelName: 'Rock_3_C_Color1',
    transform: ROCK_BUSH_TRANSFORM,
    metadata: {
      connectsTo: 'FLOOR',
      blocksLineOfSight: true,
    },
  }),
  createKayKitAsset({
    id: 'kaykit.forest_rock_3_d',
    slug: 'kaykit-forest-rock-3-d',
    name: 'KayKit Forest Rock 3 D',
    category: 'prop',
    modelName: 'Rock_3_D_Color1',
    transform: ROCK_BUSH_TRANSFORM,
    metadata: {
      connectsTo: 'FLOOR',
      blocksLineOfSight: true,
    },
  }),
  createKayKitAsset({
    id: 'kaykit.forest_rock_3_e',
    slug: 'kaykit-forest-rock-3-e',
    name: 'KayKit Forest Rock 3 E',
    category: 'prop',
    modelName: 'Rock_3_E_Color1',
    transform: ROCK_BUSH_TRANSFORM,
    metadata: {
      connectsTo: 'FLOOR',
      blocksLineOfSight: true,
    },
  }),
  createKayKitAsset({
    id: 'kaykit.forest_rock_3_f',
    slug: 'kaykit-forest-rock-3-f',
    name: 'KayKit Forest Rock 3 F',
    category: 'prop',
    modelName: 'Rock_3_F_Color1',
    transform: ROCK_BUSH_TRANSFORM,
    metadata: {
      connectsTo: 'FLOOR',
      blocksLineOfSight: true,
    },
  }),
  createKayKitAsset({
    id: 'kaykit.forest_rock_3_g',
    slug: 'kaykit-forest-rock-3-g',
    name: 'KayKit Forest Rock 3 G',
    category: 'prop',
    modelName: 'Rock_3_G_Color1',
    transform: ROCK_BUSH_TRANSFORM,
    metadata: {
      connectsTo: 'FLOOR',
      blocksLineOfSight: true,
    },
  }),
  createKayKitAsset({
    id: 'kaykit.forest_rock_3_h',
    slug: 'kaykit-forest-rock-3-h',
    name: 'KayKit Forest Rock 3 H',
    category: 'prop',
    modelName: 'Rock_3_H_Color1',
    transform: ROCK_BUSH_TRANSFORM,
    metadata: {
      connectsTo: 'FLOOR',
      blocksLineOfSight: true,
    },
  }),
  createKayKitAsset({
    id: 'kaykit.forest_rock_3_i',
    slug: 'kaykit-forest-rock-3-i',
    name: 'KayKit Forest Rock 3 I',
    category: 'prop',
    modelName: 'Rock_3_I_Color1',
    transform: ROCK_BUSH_TRANSFORM,
    metadata: {
      connectsTo: 'FLOOR',
      blocksLineOfSight: true,
    },
  }),
  createKayKitAsset({
    id: 'kaykit.forest_rock_3_j',
    slug: 'kaykit-forest-rock-3-j',
    name: 'KayKit Forest Rock 3 J',
    category: 'prop',
    modelName: 'Rock_3_J_Color1',
    transform: ROCK_BUSH_TRANSFORM,
    metadata: {
      connectsTo: 'FLOOR',
      blocksLineOfSight: true,
    },
  }),
  createKayKitAsset({
    id: 'kaykit.forest_rock_3_k',
    slug: 'kaykit-forest-rock-3-k',
    name: 'KayKit Forest Rock 3 K',
    category: 'prop',
    modelName: 'Rock_3_K_Color1',
    transform: ROCK_BUSH_TRANSFORM,
    metadata: {
      connectsTo: 'FLOOR',
      blocksLineOfSight: true,
    },
  }),
  createKayKitAsset({
    id: 'kaykit.forest_rock_3_l',
    slug: 'kaykit-forest-rock-3-l',
    name: 'KayKit Forest Rock 3 L',
    category: 'prop',
    modelName: 'Rock_3_L_Color1',
    transform: ROCK_BUSH_TRANSFORM,
    metadata: {
      connectsTo: 'FLOOR',
      blocksLineOfSight: true,
    },
  }),
  createKayKitAsset({
    id: 'kaykit.forest_rock_3_m',
    slug: 'kaykit-forest-rock-3-m',
    name: 'KayKit Forest Rock 3 M',
    category: 'prop',
    modelName: 'Rock_3_M_Color1',
    transform: ROCK_BUSH_TRANSFORM,
    metadata: {
      connectsTo: 'FLOOR',
      blocksLineOfSight: true,
    },
  }),
  createKayKitAsset({
    id: 'kaykit.forest_rock_3_n',
    slug: 'kaykit-forest-rock-3-n',
    name: 'KayKit Forest Rock 3 N',
    category: 'prop',
    modelName: 'Rock_3_N_Color1',
    transform: ROCK_BUSH_TRANSFORM,
    metadata: {
      connectsTo: 'FLOOR',
      blocksLineOfSight: true,
    },
  }),
  createKayKitAsset({
    id: 'kaykit.forest_rock_3_o',
    slug: 'kaykit-forest-rock-3-o',
    name: 'KayKit Forest Rock 3 O',
    category: 'prop',
    modelName: 'Rock_3_O_Color1',
    transform: ROCK_BUSH_TRANSFORM,
    metadata: {
      connectsTo: 'FLOOR',
      blocksLineOfSight: true,
    },
  }),
  createKayKitAsset({
    id: 'kaykit.forest_rock_3_p',
    slug: 'kaykit-forest-rock-3-p',
    name: 'KayKit Forest Rock 3 P',
    category: 'prop',
    modelName: 'Rock_3_P_Color1',
    transform: ROCK_BUSH_TRANSFORM,
    metadata: {
      connectsTo: 'FLOOR',
      blocksLineOfSight: true,
    },
  }),
  createKayKitAsset({
    id: 'kaykit.forest_rock_3_q',
    slug: 'kaykit-forest-rock-3-q',
    name: 'KayKit Forest Rock 3 Q',
    category: 'prop',
    modelName: 'Rock_3_Q_Color1',
    transform: ROCK_BUSH_TRANSFORM,
    metadata: {
      connectsTo: 'FLOOR',
      blocksLineOfSight: true,
    },
  }),
  createKayKitAsset({
    id: 'kaykit.forest_rock_3_r',
    slug: 'kaykit-forest-rock-3-r',
    name: 'KayKit Forest Rock 3 R',
    category: 'prop',
    modelName: 'Rock_3_R_Color1',
    transform: ROCK_BUSH_TRANSFORM,
    metadata: {
      connectsTo: 'FLOOR',
      blocksLineOfSight: true,
    },
  }),
  createKayKitAsset({
    id: 'kaykit.forest_tree_1_b',
    slug: 'kaykit-forest-tree-1-b',
    name: 'KayKit Forest Tree 1 B',
    category: 'prop',
    modelName: 'Tree_1_B_Color1',
    transform: TREE_TRANSFORM,
    metadata: {
      connectsTo: 'FLOOR',
      blocksLineOfSight: true,
    },
  }),
  createKayKitAsset({
    id: 'kaykit.forest_tree_1_c',
    slug: 'kaykit-forest-tree-1-c',
    name: 'KayKit Forest Tree 1 C',
    category: 'prop',
    modelName: 'Tree_1_C_Color1',
    transform: TREE_TRANSFORM,
    metadata: {
      connectsTo: 'FLOOR',
      blocksLineOfSight: true,
    },
  }),
  createKayKitAsset({
    id: 'kaykit.forest_tree_2_b',
    slug: 'kaykit-forest-tree-2-b',
    name: 'KayKit Forest Tree 2 B',
    category: 'prop',
    modelName: 'Tree_2_B_Color1',
    transform: TREE_TRANSFORM,
    metadata: {
      connectsTo: 'FLOOR',
      blocksLineOfSight: true,
    },
  }),
  createKayKitAsset({
    id: 'kaykit.forest_tree_2_c',
    slug: 'kaykit-forest-tree-2-c',
    name: 'KayKit Forest Tree 2 C',
    category: 'prop',
    modelName: 'Tree_2_C_Color1',
    transform: TREE_TRANSFORM,
    metadata: {
      connectsTo: 'FLOOR',
      blocksLineOfSight: true,
    },
  }),
  createKayKitAsset({
    id: 'kaykit.forest_tree_2_d',
    slug: 'kaykit-forest-tree-2-d',
    name: 'KayKit Forest Tree 2 D',
    category: 'prop',
    modelName: 'Tree_2_D_Color1',
    transform: TREE_TRANSFORM,
    metadata: {
      connectsTo: 'FLOOR',
      blocksLineOfSight: true,
    },
  }),
  createKayKitAsset({
    id: 'kaykit.forest_tree_2_e',
    slug: 'kaykit-forest-tree-2-e',
    name: 'KayKit Forest Tree 2 E',
    category: 'prop',
    modelName: 'Tree_2_E_Color1',
    transform: TREE_TRANSFORM,
    metadata: {
      connectsTo: 'FLOOR',
      blocksLineOfSight: true,
    },
  }),
  createKayKitAsset({
    id: 'kaykit.forest_tree_3_a',
    slug: 'kaykit-forest-tree-3-a',
    name: 'KayKit Forest Tree 3 A',
    category: 'prop',
    modelName: 'Tree_3_A_Color1',
    transform: TREE_TRANSFORM,
    metadata: {
      connectsTo: 'FLOOR',
      blocksLineOfSight: true,
    },
  }),
  createKayKitAsset({
    id: 'kaykit.forest_tree_3_b',
    slug: 'kaykit-forest-tree-3-b',
    name: 'KayKit Forest Tree 3 B',
    category: 'prop',
    modelName: 'Tree_3_B_Color1',
    transform: TREE_TRANSFORM,
    metadata: {
      connectsTo: 'FLOOR',
      blocksLineOfSight: true,
    },
  }),
  createKayKitAsset({
    id: 'kaykit.forest_tree_3_c',
    slug: 'kaykit-forest-tree-3-c',
    name: 'KayKit Forest Tree 3 C',
    category: 'prop',
    modelName: 'Tree_3_C_Color1',
    transform: TREE_TRANSFORM,
    metadata: {
      connectsTo: 'FLOOR',
      blocksLineOfSight: true,
    },
  }),
  createKayKitAsset({
    id: 'kaykit.forest_tree_4_a',
    slug: 'kaykit-forest-tree-4-a',
    name: 'KayKit Forest Tree 4 A',
    category: 'prop',
    modelName: 'Tree_4_A_Color1',
    transform: TREE_TRANSFORM,
    metadata: {
      connectsTo: 'FLOOR',
      blocksLineOfSight: true,
    },
  }),
  createKayKitAsset({
    id: 'kaykit.forest_tree_4_b',
    slug: 'kaykit-forest-tree-4-b',
    name: 'KayKit Forest Tree 4 B',
    category: 'prop',
    modelName: 'Tree_4_B_Color1',
    transform: TREE_TRANSFORM,
    metadata: {
      connectsTo: 'FLOOR',
      blocksLineOfSight: true,
    },
  }),
  createKayKitAsset({
    id: 'kaykit.forest_tree_4_c',
    slug: 'kaykit-forest-tree-4-c',
    name: 'KayKit Forest Tree 4 C',
    category: 'prop',
    modelName: 'Tree_4_C_Color1',
    transform: TREE_TRANSFORM,
    metadata: {
      connectsTo: 'FLOOR',
      blocksLineOfSight: true,
    },
  }),
  createKayKitAsset({
    id: 'kaykit.forest_tree_bare_1_b',
    slug: 'kaykit-forest-tree-bare-1-b',
    name: 'KayKit Forest Tree Bare 1 B',
    category: 'prop',
    modelName: 'Tree_Bare_1_B_Color1',
    transform: TREE_TRANSFORM,
    metadata: {
      connectsTo: 'FLOOR',
      blocksLineOfSight: true,
    },
  }),
  createKayKitAsset({
    id: 'kaykit.forest_tree_bare_1_c',
    slug: 'kaykit-forest-tree-bare-1-c',
    name: 'KayKit Forest Tree Bare 1 C',
    category: 'prop',
    modelName: 'Tree_Bare_1_C_Color1',
    transform: TREE_TRANSFORM,
    metadata: {
      connectsTo: 'FLOOR',
      blocksLineOfSight: true,
    },
  }),
  createKayKitAsset({
    id: 'kaykit.forest_tree_bare_2_a',
    slug: 'kaykit-forest-tree-bare-2-a',
    name: 'KayKit Forest Tree Bare 2 A',
    category: 'prop',
    modelName: 'Tree_Bare_2_A_Color1',
    transform: TREE_TRANSFORM,
    metadata: {
      connectsTo: 'FLOOR',
      blocksLineOfSight: true,
    },
  }),
  createKayKitAsset({
    id: 'kaykit.forest_tree_bare_2_b',
    slug: 'kaykit-forest-tree-bare-2-b',
    name: 'KayKit Forest Tree Bare 2 B',
    category: 'prop',
    modelName: 'Tree_Bare_2_B_Color1',
    transform: TREE_TRANSFORM,
    metadata: {
      connectsTo: 'FLOOR',
      blocksLineOfSight: true,
    },
  }),
  createKayKitAsset({
    id: 'kaykit.forest_tree_bare_2_c',
    slug: 'kaykit-forest-tree-bare-2-c',
    name: 'KayKit Forest Tree Bare 2 C',
    category: 'prop',
    modelName: 'Tree_Bare_2_C_Color1',
    transform: TREE_TRANSFORM,
    metadata: {
      connectsTo: 'FLOOR',
      blocksLineOfSight: true,
    },
  }),
]
